/**
 * 版权声明页面
 * 路由：/copyright
 */

import { LocalizedLink } from "@/components/i18n/LocalizedLink";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import { ChevronRight } from "lucide-react";
import type { Metadata } from "next";
import type { Locale } from "@/lib/i18n/config";

interface CopyrightPageProps {
  params: Promise<{ locale: Locale }>;
}

export async function generateMetadata({
  params,
}: CopyrightPageProps): Promise<Metadata> {
  const { locale } = await params;
  const isEn = locale === "en";
  return {
    title: isEn ? "Copyright Notice | Recipe Zen" : "版权声明 | Recipe Zen",
    description: isEn
      ? "Copyright notice for Recipe Zen. Learn ownership and usage rules for site content."
      : "Recipe Zen 版权声明，了解本网站内容的版权归属和使用规则。",
  };
}

export default async function CopyrightPage({ params }: CopyrightPageProps) {
  const { locale } = await params;
  const isEn = locale === "en";
  const lastUpdated = isEn ? "December 31, 2024" : "2024年12月31日";
  const currentYear = new Date().getFullYear();

  return (
    <div className="min-h-screen bg-cream">
      <Header />

      <main className="max-w-4xl mx-auto px-4 sm:px-8 py-8 sm:py-12">
        {/* 面包屑导航 */}
        <nav className="flex items-center gap-2 text-sm text-textGray mb-6">
          <LocalizedLink href="/" className="hover:text-brownWarm transition-colors">
            {isEn ? "Home" : "首页"}
          </LocalizedLink>
          <ChevronRight className="w-4 h-4" />
          <span className="text-textDark">
            {isEn ? "Copyright Notice" : "版权声明"}
          </span>
        </nav>

        <article className="bg-white rounded-xl p-6 sm:p-10 shadow-sm">
          <h1 className="text-3xl font-serif font-medium text-textDark mb-4">
            {isEn ? "Copyright Notice" : "版权声明"}
          </h1>
          <p className="text-sm text-textGray mb-8">
            {isEn ? "Last updated: " : "最后更新："}
            {lastUpdated}
          </p>

          <div className="prose prose-lg max-w-none prose-headings:font-serif prose-headings:text-textDark prose-p:text-textGray prose-li:text-textGray">
            <p>
              © {currentYear} Recipe Zen.{" "}
              {isEn ? "All rights reserved." : "保留所有权利。"}
            </p>

            <h2>{isEn ? "1. Copyright Ownership" : "一、版权归属"}</h2>
            <p>
              {isEn
                ? "Unless otherwise stated, all content published on Recipe Zen, including but not limited to:"
                : "除特别注明外，本网站（Recipe Zen）上发布的所有内容，包括但不限于："}
            </p>
            <ul>
              <li>{isEn ? "Site design, layout, visual elements" : "网站设计、界面布局、视觉元素"}</li>
              <li>{isEn ? "Recipes, cooking steps, nutrition information" : "食谱内容、烹饪步骤、营养信息"}</li>
              <li>{isEn ? "Blog articles and editorial content" : "博客文章、资讯内容"}</li>
              <li>{isEn ? "Images, illustrations, photography" : "图片、插图、摄影作品"}</li>
              <li>{isEn ? "Brand assets, logos, icons" : "品牌标识、Logo、图标"}</li>
              <li>{isEn ? "Software code and databases" : "软件代码、数据库"}</li>
            </ul>
            <p>
              {isEn
                ? "are the intellectual property of Recipe Zen and its creators, protected by applicable copyright laws."
                : "均为 Recipe Zen 及其内容创作者的知识产权，受中华人民共和国著作权法及相关法律法规保护。"}
            </p>

            <h2>{isEn ? "2. AI-Generated Content" : "二、AI 生成内容说明"}</h2>
            <p>
              {isEn
                ? "Some recipes are assisted by AI. Regarding AI-generated content:"
                : "本网站部分食谱内容由人工智能技术辅助生成。关于 AI 生成内容的版权："}
            </p>
            <ul>
              <li>{isEn ? "AI recipes are edited and reviewed before publication; copyrights belong to Recipe Zen." : "AI 生成的食谱经过编辑审核后发布，版权归属于 Recipe Zen"}</li>
              <li>{isEn ? "Personal recipes generated via AI custom are licensed for user use." : "用户使用 AI 定制功能生成的个人食谱，用户享有使用权"}</li>
              <li>{isEn ? "AI content may resemble existing works; contact us for infringement concerns." : "AI 生成内容可能与已有作品存在相似性，如有侵权请联系我们处理"}</li>
            </ul>

            <h2>{isEn ? "3. Image Copyrights" : "三、图片版权"}</h2>
            <h3>{isEn ? "3.1 Original images" : "3.1 原创图片"}</h3>
            <p>
              {isEn
                ? "Original food photography on this site is owned by Recipe Zen and may not be used without permission."
                : "本网站的原创美食摄影作品版权归 Recipe Zen 所有，未经许可不得使用。"}
            </p>

            <h3>{isEn ? "3.2 AI-generated images" : "3.2 AI 生成图片"}</h3>
            <p>
              {isEn
                ? "Some recipe images are generated by AI. These images:"
                : "部分食谱配图由 AI 图像生成技术创作，这些图片："}
            </p>
            <ul>
              <li>{isEn ? "Are for display and illustrative purposes only." : "仅用于展示和说明目的"}</li>
              <li>{isEn ? "May differ from real cooking results." : "可能与实际烹饪成品存在差异"}</li>
              <li>{isEn ? "Follow the usage terms of the AI service provider." : "版权归属遵循相关 AI 服务的使用条款"}</li>
            </ul>

            <h3>{isEn ? "3.3 User-uploaded images" : "3.3 用户上传图片"}</h3>
            <p>
              {isEn
                ? "Users must ensure they have rights or authorization for uploaded images. Uploading grants Recipe Zen permission to use them on this site."
                : "用户上传的图片，用户应确保拥有相应版权或使用授权。上传即视为授权 Recipe Zen 在本网站范围内使用。"}
            </p>

            <h2>{isEn ? "4. Fair Use" : "四、合理使用"}</h2>
            <p>{isEn ? "You may use site content in the following cases:" : "在以下情况下，您可以合理使用本网站内容："}</p>
            <ul>
              <li>
                <strong>{isEn ? "Personal study" : "个人学习"}</strong>
                {isEn
                  ? ": reasonable citation for learning or research with attribution."
                  : "：出于个人学习、研究目的，可以适量引用并注明出处"}
              </li>
              <li>
                <strong>{isEn ? "Social sharing" : "社交分享"}</strong>
                {isEn
                  ? ": share recipe links via the site’s sharing features."
                  : "：可以通过网站提供的分享功能，分享食谱链接到社交媒体"}
              </li>
              <li>
                <strong>{isEn ? "News reporting" : "新闻报道"}</strong>
                {isEn
                  ? ": appropriate citation with source attribution."
                  : "：媒体进行新闻报道时，可以适当引用并注明来源"}
              </li>
              <li>
                <strong>{isEn ? "Education" : "教育目的"}</strong>
                {isEn
                  ? ": educational institutions may use with attribution."
                  : "：教育机构用于教学目的时，可以适当使用并注明来源"}
              </li>
            </ul>

            <h2>{isEn ? "5. Prohibited Uses" : "五、禁止行为"}</h2>
            <p>{isEn ? "Without written permission, the following are prohibited:" : "未经书面许可，禁止以下行为："}</p>
            <ul>
              <li>{isEn ? "Copying or republishing recipes for commercial use." : "复制、转载本网站的食谱内容用于商业目的"}</li>
              <li>{isEn ? "Bulk downloading or scraping site content." : "批量下载或抓取网站内容"}</li>
              <li>{isEn ? "Removing or altering copyright notices." : "去除或修改版权标识"}</li>
              <li>{isEn ? "Using site content to create derivative commercial products." : "将本网站内容用于制作衍生商业产品"}</li>
              <li>{isEn ? "Impersonating the Recipe Zen brand." : "冒用 Recipe Zen 品牌或标识"}</li>
              <li>{isEn ? "Publishing content under our name on other platforms." : "在其他平台上以本网站名义发布内容"}</li>
            </ul>

            <h2>{isEn ? "6. Reprint Guidelines" : "六、转载规范"}</h2>
            <p>{isEn ? "If you wish to reprint our content, please follow these rules:" : "如需转载本网站内容，请遵守以下规范："}</p>
            <ol>
              <li>{isEn ? "Contact us in advance for written permission." : "事先联系我们获得书面授权"}</li>
              <li>{isEn ? 'Clearly attribute the source: "Source: Recipe Zen (recipezen.com)".' : "在显著位置注明来源：\"来源：Recipe Zen (recipezen.com)\""}</li>
              <li>{isEn ? "Provide a link to the original page." : "提供指向原文的链接"}</li>
              <li>{isEn ? "Do not distort or modify the content." : "不得对内容进行歪曲或篡改"}</li>
              <li>{isEn ? 'For non-commercial use, add: "For learning only; copyright belongs to the author".' : "非商业性转载需注明\"仅供学习交流，版权归原作者所有\""}</li>
            </ol>

            <h2>{isEn ? "7. Infringement Claims" : "七、侵权投诉"}</h2>
            <p>
              {isEn
                ? "If you believe content on this site infringes your rights, please provide:"
                : "如果您认为本网站上的内容侵犯了您的合法权益，请提供以下信息联系我们："}
            </p>
            <ul>
              <li>{isEn ? "Your identification" : "您的身份证明"}</li>
              <li>{isEn ? "Links to the allegedly infringing content" : "涉嫌侵权内容的链接"}</li>
              <li>{isEn ? "Proof of copyright ownership" : "您拥有版权的证明材料"}</li>
              <li>{isEn ? "A detailed description of the infringement" : "侵权情况的详细说明"}</li>
              <li>{isEn ? "Your contact information" : "您的联系方式"}</li>
            </ul>
            <p>
              {isEn
                ? "We will investigate promptly upon receiving a valid complaint and respond within a reasonable time."
                : "我们会在收到有效投诉后尽快核实处理，并在合理时间内给予回复。"}
            </p>

            <h2>{isEn ? "8. Third-Party Content" : "八、第三方内容"}</h2>
            <p>
              {isEn
                ? "The site may include third-party links or content. Copyrights belong to their original creators. We provide it for informational purposes only. Contact the rights holder for issues."
                : "本网站可能包含第三方的链接或内容。这些第三方内容的版权归其原始创作者所有，我们仅作为信息展示平台。如有版权问题，请直接联系相关权利人。"}
            </p>

            <h2>{isEn ? "9. Updates to This Notice" : "九、版权声明更新"}</h2>
            <p>
              {isEn
                ? "We may update this notice due to legal or business changes. Updates will be posted here; please review periodically."
                : "我们可能会根据法律变化或业务需要更新本版权声明。更新后的声明将在本页面发布，建议您定期查阅。"}
            </p>

            <h2>{isEn ? "10. Contact Us" : "十、联系我们"}</h2>
            <p>
              {isEn
                ? "For copyright-related inquiries, contact us at:"
                : "如有版权相关问题，请通过以下方式联系我们："}
            </p>
            <ul>
              <li>{isEn ? "Copyright: copyright@recipezen.com" : "版权事务邮箱：copyright@recipezen.com"}</li>
              <li>{isEn ? "General inquiries: support@recipezen.com" : "一般咨询邮箱：support@recipezen.com"}</li>
            </ul>

            <div className="mt-8 p-4 bg-lightGray/50 rounded-lg">
              <p className="text-sm text-textGray mb-0">
                <strong>{isEn ? "Statement" : "声明"}</strong>
                {isEn
                  ? ": Recipe Zen respects intellectual property and is committed to protecting original content. We ask all users to help maintain a healthy copyright environment."
                  : "：Recipe Zen 尊重知识产权，致力于保护原创内容。我们呼吁所有用户共同维护健康的网络版权环境。"}
              </p>
            </div>
          </div>
        </article>

        {/* 相关链接 */}
        <div className="mt-8 flex flex-wrap gap-4 justify-center text-sm">
          <LocalizedLink
            href="/privacy"
            className="text-textGray hover:text-brownWarm transition-colors"
          >
            {isEn ? "Privacy Policy" : "隐私政策"}
          </LocalizedLink>
          <span className="text-lightGray">|</span>
          <LocalizedLink
            href="/terms"
            className="text-textGray hover:text-brownWarm transition-colors"
          >
            {isEn ? "Terms" : "使用条款"}
          </LocalizedLink>
          <span className="text-lightGray">|</span>
          <LocalizedLink
            href="/about"
            className="text-textGray hover:text-brownWarm transition-colors"
          >
            {isEn ? "About" : "关于我们"}
          </LocalizedLink>
        </div>
      </main>

      <Footer />
    </div>
  );
}
