const fs = require('fs');
const path = 'lib/ai/default-prompts.ts';
const promptPath = 'scripts/_tmp_recipe_prompt.txt';
let content = fs.readFileSync(path, 'utf8');
const marker = 'key: "recipe_generate"';
const idx = content.indexOf(marker);
if (idx === -1) throw new Error('recipe_generate not found');
const sysIdx = content.indexOf('systemPrompt:', idx);
if (sysIdx === -1) throw new Error('systemPrompt not found');
const startTick = content.indexOf('`', sysIdx);
if (startTick === -1) throw new Error('start backtick not found');
const promptIdx = content.indexOf('\n    prompt:', startTick);
if (promptIdx === -1) throw new Error('prompt field not found');
const endTick = content.lastIndexOf('`', promptIdx);
if (endTick === -1 || endTick <= startTick) throw new Error('end backtick not found');
let prompt = fs.readFileSync(promptPath, 'utf8');
prompt = prompt.replace(/\s+$/, '');
const escaped = prompt.replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
content = content.slice(0, startTick + 1) + escaped + content.slice(endTick);
fs.writeFileSync(path, content, 'utf8');
