/**
 * Seed base tag data (scene/method/taste/crowd/occasion).
 *
 * Run: npx tsx scripts/seed-tags.ts
 */

import { config } from "dotenv";
import { PrismaClient } from "@prisma/client";
import { Pool } from "pg";
import { PrismaPg } from "@prisma/adapter-pg";

config({ path: ".env.local" });

const connectionString = process.env.DATABASE_URL;
if (!connectionString) {
  throw new Error("DATABASE_URL is not set. Please check .env.local file.");
}

const pool = new Pool({ connectionString });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

type TagSeed = {
  id: string;
  type: "scene" | "method" | "taste" | "crowd" | "occasion";
  nameZh: string;
  nameEn: string;
  slug: string;
  sortOrder: number;
};

const tags: TagSeed[] = [
  // 场景
  {
    id: "scene-01",
    type: "scene",
    nameZh: "早餐",
    nameEn: "Breakfast",
    slug: "breakfast",
    sortOrder: 1,
  },
  {
    id: "scene-02",
    type: "scene",
    nameZh: "午餐",
    nameEn: "Lunch",
    slug: "lunch",
    sortOrder: 2,
  },
  {
    id: "scene-03",
    type: "scene",
    nameZh: "晚餐",
    nameEn: "Dinner",
    slug: "dinner",
    sortOrder: 3,
  },
  {
    id: "scene-04",
    type: "scene",
    nameZh: "下午茶",
    nameEn: "Afternoon Tea",
    slug: "afternoon-tea",
    sortOrder: 4,
  },
  {
    id: "scene-05",
    type: "scene",
    nameZh: "夜宵",
    nameEn: "Late Night Snack",
    slug: "late-night-snack",
    sortOrder: 5,
  },
  {
    id: "scene-06",
    type: "scene",
    nameZh: "便当",
    nameEn: "Bento",
    slug: "bento",
    sortOrder: 6,
  },
  {
    id: "scene-07",
    type: "scene",
    nameZh: "快手菜",
    nameEn: "Quick Dish",
    slug: "quick-dish",
    sortOrder: 7,
  },
  {
    id: "scene-08",
    type: "scene",
    nameZh: "懒人菜",
    nameEn: "Lazy Cooking",
    slug: "lazy-cooking",
    sortOrder: 8,
  },
  {
    id: "scene-09",
    type: "scene",
    nameZh: "下酒菜",
    nameEn: "Drinking Snack",
    slug: "drinking-snack",
    sortOrder: 9,
  },
  {
    id: "scene-10",
    type: "scene",
    nameZh: "下饭菜",
    nameEn: "Rice Pairing",
    slug: "rice-pairing",
    sortOrder: 10,
  },
  {
    id: "scene-11",
    type: "scene",
    nameZh: "减脂餐",
    nameEn: "Weight Loss Meal",
    slug: "weight-loss-meal",
    sortOrder: 11,
  },
  {
    id: "scene-12",
    type: "scene",
    nameZh: "健身餐",
    nameEn: "Fitness Meal",
    slug: "fitness-meal",
    sortOrder: 12,
  },
  {
    id: "scene-13",
    type: "scene",
    nameZh: "儿童餐",
    nameEn: "Kids Meal",
    slug: "kids-meal",
    sortOrder: 13,
  },
  {
    id: "scene-14",
    type: "scene",
    nameZh: "月子餐",
    nameEn: "Postpartum Meal",
    slug: "postpartum-meal",
    sortOrder: 14,
  },
  {
    id: "scene-15",
    type: "scene",
    nameZh: "老人餐",
    nameEn: "Senior Meal",
    slug: "senior-meal",
    sortOrder: 15,
  },

  // 烹饪方法
  {
    id: "method-01",
    type: "method",
    nameZh: "炒",
    nameEn: "Stir-Fry",
    slug: "stir-fry",
    sortOrder: 1,
  },
  {
    id: "method-02",
    type: "method",
    nameZh: "蒸",
    nameEn: "Steam",
    slug: "steam",
    sortOrder: 2,
  },
  {
    id: "method-03",
    type: "method",
    nameZh: "炖",
    nameEn: "Stew",
    slug: "stew",
    sortOrder: 3,
  },
  {
    id: "method-04",
    type: "method",
    nameZh: "烤",
    nameEn: "Bake/Roast",
    slug: "bake-roast",
    sortOrder: 4,
  },
  {
    id: "method-05",
    type: "method",
    nameZh: "煮",
    nameEn: "Boil",
    slug: "boil",
    sortOrder: 5,
  },
  {
    id: "method-06",
    type: "method",
    nameZh: "煎",
    nameEn: "Pan-Fry",
    slug: "pan-fry",
    sortOrder: 6,
  },
  {
    id: "method-07",
    type: "method",
    nameZh: "炸",
    nameEn: "Deep-Fry",
    slug: "deep-fry",
    sortOrder: 7,
  },
  {
    id: "method-08",
    type: "method",
    nameZh: "烧",
    nameEn: "Braise",
    slug: "braise",
    sortOrder: 8,
  },
  {
    id: "method-09",
    type: "method",
    nameZh: "焖",
    nameEn: "Simmer",
    slug: "simmer",
    sortOrder: 9,
  },
  {
    id: "method-10",
    type: "method",
    nameZh: "拌",
    nameEn: "Toss/Mix",
    slug: "toss-mix",
    sortOrder: 10,
  },
  {
    id: "method-11",
    type: "method",
    nameZh: "卤",
    nameEn: "Braise in Soy Sauce",
    slug: "braise-in-soy-sauce",
    sortOrder: 11,
  },
  {
    id: "method-12",
    type: "method",
    nameZh: "煲",
    nameEn: "Soup Pot",
    slug: "soup-pot",
    sortOrder: 12,
  },
  {
    id: "method-13",
    type: "method",
    nameZh: "炝",
    nameEn: "Quick-Fry",
    slug: "quick-fry",
    sortOrder: 13,
  },
  {
    id: "method-14",
    type: "method",
    nameZh: "腌",
    nameEn: "Pickle/Marinate",
    slug: "pickle-marinate",
    sortOrder: 14,
  },
  {
    id: "method-15",
    type: "method",
    nameZh: "熏",
    nameEn: "Smoke",
    slug: "smoke",
    sortOrder: 15,
  },
  {
    id: "method-16",
    type: "method",
    nameZh: "凉拌",
    nameEn: "Cold Dish",
    slug: "cold-dish",
    sortOrder: 16,
  },
  {
    id: "method-17",
    type: "method",
    nameZh: "烙",
    nameEn: "Griddle",
    slug: "griddle",
    sortOrder: 17,
  },
  {
    id: "method-18",
    type: "method",
    nameZh: "扒",
    nameEn: "Sauté",
    slug: "saute",
    sortOrder: 18,
  },
  {
    id: "method-19",
    type: "method",
    nameZh: "爆",
    nameEn: "Quick-Blast",
    slug: "quick-blast",
    sortOrder: 19,
  },
  {
    id: "method-20",
    type: "method",
    nameZh: "醉",
    nameEn: "Wine-Soaked",
    slug: "wine-soaked",
    sortOrder: 20,
  },

  // 口味
  {
    id: "flavor-01",
    type: "taste",
    nameZh: "咸香",
    nameEn: "Savory",
    slug: "savory",
    sortOrder: 1,
  },
  {
    id: "flavor-02",
    type: "taste",
    nameZh: "麻辣",
    nameEn: "Spicy",
    slug: "spicy",
    sortOrder: 2,
  },
  {
    id: "flavor-03",
    type: "taste",
    nameZh: "香辣",
    nameEn: "Hot & Spicy",
    slug: "hot-spicy",
    sortOrder: 3,
  },
  {
    id: "flavor-04",
    type: "taste",
    nameZh: "酸辣",
    nameEn: "Sour & Spicy",
    slug: "sour-spicy",
    sortOrder: 4,
  },
  {
    id: "flavor-05",
    type: "taste",
    nameZh: "糖醋",
    nameEn: "Sweet & Sour",
    slug: "sweet-sour",
    sortOrder: 5,
  },
  {
    id: "flavor-06",
    type: "taste",
    nameZh: "清淡",
    nameEn: "Light",
    slug: "light",
    sortOrder: 6,
  },
  {
    id: "flavor-07",
    type: "taste",
    nameZh: "鲜香",
    nameEn: "Umami",
    slug: "umami",
    sortOrder: 7,
  },
  {
    id: "flavor-08",
    type: "taste",
    nameZh: "甜味",
    nameEn: "Sweet",
    slug: "sweet",
    sortOrder: 8,
  },
  {
    id: "flavor-09",
    type: "taste",
    nameZh: "咸鲜",
    nameEn: "Salty & Fresh",
    slug: "salty-fresh",
    sortOrder: 9,
  },
  {
    id: "flavor-10",
    type: "taste",
    nameZh: "酱香",
    nameEn: "Sauce Flavor",
    slug: "sauce-flavor",
    sortOrder: 10,
  },
  {
    id: "flavor-11",
    type: "taste",
    nameZh: "蒜香",
    nameEn: "Garlic Flavor",
    slug: "garlic-flavor",
    sortOrder: 11,
  },
  {
    id: "flavor-12",
    type: "taste",
    nameZh: "椒盐",
    nameEn: "Salt & Pepper",
    slug: "salt-pepper",
    sortOrder: 12,
  },
  {
    id: "flavor-13",
    type: "taste",
    nameZh: "孜然",
    nameEn: "Cumin",
    slug: "cumin",
    sortOrder: 13,
  },
  {
    id: "flavor-14",
    type: "taste",
    nameZh: "五香",
    nameEn: "Five-Spice",
    slug: "five-spice",
    sortOrder: 14,
  },
  {
    id: "flavor-15",
    type: "taste",
    nameZh: "葱香",
    nameEn: "Scallion Flavor",
    slug: "scallion-flavor",
    sortOrder: 15,
  },
  {
    id: "flavor-16",
    type: "taste",
    nameZh: "姜味",
    nameEn: "Ginger Flavor",
    slug: "ginger-flavor",
    sortOrder: 16,
  },
  {
    id: "flavor-17",
    type: "taste",
    nameZh: "酒香",
    nameEn: "Wine Aroma",
    slug: "wine-aroma",
    sortOrder: 17,
  },
  {
    id: "flavor-18",
    type: "taste",
    nameZh: "茶香",
    nameEn: "Tea Flavor",
    slug: "tea-flavor",
    sortOrder: 18,
  },
  {
    id: "flavor-19",
    type: "taste",
    nameZh: "烟熏",
    nameEn: "Smoky",
    slug: "smoky",
    sortOrder: 19,
  },
  {
    id: "flavor-20",
    type: "taste",
    nameZh: "清爽",
    nameEn: "Refreshing",
    slug: "refreshing",
    sortOrder: 20,
  },

  // 适宜人群
  {
    id: "suitable-01",
    type: "crowd",
    nameZh: "孕妇",
    nameEn: "Pregnant Women",
    slug: "pregnant-women",
    sortOrder: 1,
  },
  {
    id: "suitable-02",
    type: "crowd",
    nameZh: "产妇",
    nameEn: "Postpartum Women",
    slug: "postpartum-women",
    sortOrder: 2,
  },
  {
    id: "suitable-03",
    type: "crowd",
    nameZh: "儿童",
    nameEn: "Children",
    slug: "children",
    sortOrder: 3,
  },
  {
    id: "suitable-04",
    type: "crowd",
    nameZh: "老人",
    nameEn: "Seniors",
    slug: "seniors",
    sortOrder: 4,
  },
  {
    id: "suitable-05",
    type: "crowd",
    nameZh: "糖尿病",
    nameEn: "Diabetes",
    slug: "diabetes",
    sortOrder: 5,
  },
  {
    id: "suitable-06",
    type: "crowd",
    nameZh: "高血压",
    nameEn: "Hypertension",
    slug: "hypertension",
    sortOrder: 6,
  },
  {
    id: "suitable-07",
    type: "crowd",
    nameZh: "贫血",
    nameEn: "Anemia",
    slug: "anemia",
    sortOrder: 7,
  },
  {
    id: "suitable-08",
    type: "crowd",
    nameZh: "痛风",
    nameEn: "Gout",
    slug: "gout",
    sortOrder: 8,
  },
  {
    id: "suitable-09",
    type: "crowd",
    nameZh: "肠胃不好",
    nameEn: "Digestive Issues",
    slug: "digestive-issues",
    sortOrder: 9,
  },
  {
    id: "suitable-10",
    type: "crowd",
    nameZh: "便秘",
    nameEn: "Constipation",
    slug: "constipation",
    sortOrder: 10,
  },
  {
    id: "suitable-11",
    type: "crowd",
    nameZh: "减肥人群",
    nameEn: "Weight Loss",
    slug: "weight-loss",
    sortOrder: 11,
  },
  {
    id: "suitable-12",
    type: "crowd",
    nameZh: "健身人群",
    nameEn: "Fitness",
    slug: "fitness",
    sortOrder: 12,
  },
  {
    id: "suitable-13",
    type: "crowd",
    nameZh: "上班族",
    nameEn: "Office Workers",
    slug: "office-workers",
    sortOrder: 13,
  },
  {
    id: "suitable-14",
    type: "crowd",
    nameZh: "学生",
    nameEn: "Students",
    slug: "students",
    sortOrder: 14,
  },
  {
    id: "suitable-15",
    type: "crowd",
    nameZh: "素食者",
    nameEn: "Vegetarians",
    slug: "vegetarians",
    sortOrder: 15,
  },
  {
    id: "suitable-16",
    type: "crowd",
    nameZh: "过敏体质",
    nameEn: "Allergies",
    slug: "allergies",
    sortOrder: 16,
  },
  {
    id: "suitable-17",
    type: "crowd",
    nameZh: "肾病",
    nameEn: "Kidney Disease",
    slug: "kidney-disease",
    sortOrder: 17,
  },
  {
    id: "suitable-18",
    type: "crowd",
    nameZh: "脂肪肝",
    nameEn: "Fatty Liver",
    slug: "fatty-liver",
    sortOrder: 18,
  },
  {
    id: "suitable-19",
    type: "crowd",
    nameZh: "感冒咳嗽",
    nameEn: "Cold & Cough",
    slug: "cold-cough",
    sortOrder: 19,
  },
  {
    id: "suitable-20",
    type: "crowd",
    nameZh: "熬夜人群",
    nameEn: "Night Owls",
    slug: "night-owls",
    sortOrder: 20,
  },

  // 场合
  {
    id: "occasion-01",
    type: "occasion",
    nameZh: "家常菜",
    nameEn: "Home Cooking",
    slug: "home-cooking",
    sortOrder: 1,
  },
  {
    id: "occasion-02",
    type: "occasion",
    nameZh: "宴客菜",
    nameEn: "Banquet Dish",
    slug: "banquet-dish",
    sortOrder: 2,
  },
  {
    id: "occasion-03",
    type: "occasion",
    nameZh: "春节",
    nameEn: "Chinese New Year",
    slug: "chinese-new-year",
    sortOrder: 3,
  },
  {
    id: "occasion-04",
    type: "occasion",
    nameZh: "中秋节",
    nameEn: "Mid-Autumn Festival",
    slug: "mid-autumn-festival",
    sortOrder: 4,
  },
  {
    id: "occasion-05",
    type: "occasion",
    nameZh: "端午节",
    nameEn: "Dragon Boat Festival",
    slug: "dragon-boat-festival",
    sortOrder: 5,
  },
  {
    id: "occasion-06",
    type: "occasion",
    nameZh: "元宵节",
    nameEn: "Lantern Festival",
    slug: "lantern-festival",
    sortOrder: 6,
  },
  {
    id: "occasion-07",
    type: "occasion",
    nameZh: "清明节",
    nameEn: "Qingming Festival",
    slug: "qingming-festival",
    sortOrder: 7,
  },
  {
    id: "occasion-08",
    type: "occasion",
    nameZh: "重阳节",
    nameEn: "Double Ninth Festival",
    slug: "double-ninth-festival",
    sortOrder: 8,
  },
  {
    id: "occasion-09",
    type: "occasion",
    nameZh: "生日宴",
    nameEn: "Birthday Party",
    slug: "birthday-party",
    sortOrder: 9,
  },
  {
    id: "occasion-10",
    type: "occasion",
    nameZh: "婚宴",
    nameEn: "Wedding Banquet",
    slug: "wedding-banquet",
    sortOrder: 10,
  },
  {
    id: "occasion-11",
    type: "occasion",
    nameZh: "满月酒",
    nameEn: "Full Month Celebration",
    slug: "full-month-celebration",
    sortOrder: 11,
  },
  {
    id: "occasion-12",
    type: "occasion",
    nameZh: "聚餐",
    nameEn: "Gathering",
    slug: "gathering",
    sortOrder: 12,
  },
  {
    id: "occasion-13",
    type: "occasion",
    nameZh: "野餐",
    nameEn: "Picnic",
    slug: "picnic",
    sortOrder: 13,
  },
  {
    id: "occasion-14",
    type: "occasion",
    nameZh: "烧烤",
    nameEn: "BBQ",
    slug: "bbq",
    sortOrder: 14,
  },
  {
    id: "occasion-15",
    type: "occasion",
    nameZh: "火锅",
    nameEn: "Hot Pot",
    slug: "hot-pot",
    sortOrder: 15,
  },
  {
    id: "occasion-16",
    type: "occasion",
    nameZh: "下午茶",
    nameEn: "Afternoon Tea",
    slug: "afternoon-tea-occasion",
    sortOrder: 16,
  },
  {
    id: "occasion-17",
    type: "occasion",
    nameZh: "看球赛",
    nameEn: "Watch Sports",
    slug: "watch-sports",
    sortOrder: 17,
  },
  {
    id: "occasion-18",
    type: "occasion",
    nameZh: "追剧",
    nameEn: "Binge-Watching",
    slug: "binge-watching",
    sortOrder: 18,
  },
  {
    id: "occasion-19",
    type: "occasion",
    nameZh: "周末",
    nameEn: "Weekend",
    slug: "weekend",
    sortOrder: 19,
  },
  {
    id: "occasion-20",
    type: "occasion",
    nameZh: "纪念日",
    nameEn: "Anniversary",
    slug: "anniversary",
    sortOrder: 20,
  },
];

async function main() {
  console.log(`🌱 开始导入标签数据，共 ${tags.length} 条...`);

  for (const tag of tags) {
    const record = await prisma.tag.upsert({
      where: { slug: tag.slug },
      create: {
        id: tag.id,
        type: tag.type,
        name: tag.nameZh,
        slug: tag.slug,
        sortOrder: tag.sortOrder,
        isActive: true,
      },
      update: {
        type: tag.type,
        name: tag.nameZh,
        sortOrder: tag.sortOrder,
        isActive: true,
      },
    });

    await prisma.tagTranslation.upsert({
      where: {
        tagId_locale: {
          tagId: record.id,
          locale: "en",
        },
      },
      create: {
        tagId: record.id,
        locale: "en",
        name: tag.nameEn,
        slug: tag.slug,
      },
      update: {
        name: tag.nameEn,
        slug: tag.slug,
      },
    });
  }

  console.log("✅ 标签数据导入完成");
}

main()
  .catch((error) => {
    console.error("❌ 导入失败:", error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
    await pool.end();
  });
